### ISSUE TITLE
Erstatt placeholder-knapper med ferdigstilte UI-knapper fra google drive

### ISSUE THREAD

**Issue by hanseei** [FunkWeb/spill6#102]
Tilbake-knapp, level-ikoner, pause-knapp, volum-slider (og ikon) og lyd/dempet-ikon (samt andre, men disse er de jeg ser in-game nå) kan nå erstattes med faktiske ikoner.

**Comment by vsgj** [comment]
Link til mappe for knapper: https://drive.google.com/drive/folders/1-G-p9rfeckMvN5QbFGmOGCN3HQGwclsG

**Comment by vsgj** [comment]
Oppdatering: UI assets er lagt inn i prosjektet's mappestruktur (assets>art>ui). Nå trenger de å erstattes med eksisterende UI elementer.

**Comment by Tobb50** [comment]
Holder fortsatt på med flere UI-teksturer
