### ISSUE TITLE
Pausemeny-skisse kan erstattes

### ISSUE THREAD

**Issue by hanseei** [FunkWeb/spill6#103]
Både tau-teksturer og skilt/'stigetrinn'-teksturer er ferdige, blurry/desaturert bakgrunn burde settes inn fra godot.

**Comment by vsgj** [comment]
Link til skilt-mappe (inkludert "Ekstra"): https://drive.google.com/drive/folders/1OSdEsn1tqYAp4Sf7p-7DgWUphSQahn3w

**Comment by vsgj** [comment]
Link til mappe for knapper: https://drive.google.com/drive/folders/1-G-p9rfeckMvN5QbFGmOGCN3HQGwclsG

**Comment by vsgj** [comment]
Oppdatering: UI assets er lagt inn i prosjektet's mappestruktur (assets>art>ui). Nå trenger de å erstattes med eksisterende UI elementer.
