### ISSUE TITLE
Erstatt hinder/miljø-placeholders med mer ferdige teksturer

### ISSUE THREAD

**Issue by hanseei** [FunkWeb/spill6#104]
Victoria har lagt inn teksturer av hindre og miljø, samt en måkeanimasjon, i mappene i google drive.

**Comment by NorskViking** [comment]
Nye hindrer teksturer for skogbane lagt inn og opprettet som nye scener. Lagt inn i w1m1 banen, og koblet signaler slik at spiller mister liv ved treff på hinder. Erstattet flere av de tidligere villsvinn hinderene med de nye hinderene.
