### ISSUE TITLE
Vinner-musikken spilles to ganger

### ISSUE THREAD

**Issue by nycofox** [FunkWeb/spill6#115]
Versjon testet: v0.1.4-alpha

Når man fullfører bane W1M1, så begynner vinnermusikken å spille. Etter ett sekund kommer man tilbake til hovedmenyen, og vinnermusikken spilles på nytt (avbryter den som allerede spiller).

**Comment by ghost** [comment]
mulig relatert til #71 som gjør at spilleren beveger seg over målstreken 2 ganger

**Comment by NorskViking** [comment]
Vinnermussikken virker til å spille på nytt når man blir sendt til startskjerm.
