### ISSUE TITLE
Ingen musikk når man dør

### ISSUE THREAD

**Issue by nycofox** [FunkWeb/spill6#117]
Versjon testet: v0.1.4-alpha

Før så fikk man en "trist" melodi når man døde, nå er det helt stille.

**Comment by Tobb50** [comment]
Jeg ser at man får lydeffekten om man spesifikt faller til døden i hullene, men ikke dersom man dør av å miste liv. Jeg kan få lagt til en lyd for når man dør av å miste liv.

**Comment by Tobb50** [comment]
Når man nå dør til hinder spilles det av en unik TaperLyd.
