### ISSUE TITLE
Å sette "Default Texture Repeat" til Disabled ødelegger geometri edge material

### ISSUE THREAD

**Issue by JonathanPR-Github** [FunkWeb/spill6#118]
Fikset dette problemet med å ticke Project setting, _Settinget_ Default Texture Repeat til Enabled isteden for Disabled

**Comment by ghost** [comment]
Dette førte til en bug med andre teksturer, se #187
#188 satte default til disabled og satte texture_repeat til enabled på hver map_geometry for å beholde texture repeat på disse.
