### ISSUE TITLE
Endringer i .import-filer hver gang prosjekt åpnes - legge til i .gitignore?

### ISSUE THREAD

**Issue by hanseei** [FunkWeb/spill6#119]
Rapportert fra @Tobb50 (Tobias) (og også observert av meg når jeg skulle teste en build fra en branch), .import-filer for teksturene oppdaterer seg i følge git hele tiden. Om disse er tilsvarende .meta-filene til Unity blir de generert automatisk uansett, og vil da ofte lage endringer i git. Kan disse vurderes å legges til i en .gitignore-fil?

**Comment by ghost** [comment]
.import skal bare bli laget en gang. Noe tilsvarende .meta tror jeg lagres i .godot mappen som allerede er i .gitignore
Ser at #109 ikke har med .import filer i comitten, så derfor blir de blir laget av godot når den åpnes.
