### ISSUE TITLE
"Fortsett" og " || "-bildet i pausemenyen

### ISSUE THREAD

**Issue by eturenuR** [FunkWeb/spill6#128]
I pausemenyen så må du trykke "fortsett" for å fortsette.

Det mest naturlige kan av og til være å trykke på samme sted og bildet av " || " som er øverst i høyre hjørne og samme sted som den opprinnelige "pause"-knappen.

(versjon 0.1.4)

**Comment by Tobb50** [comment]
Vi har en fungerende løsning akkurat nå, så vil si at dette blir unødvendig endring, som heller fører til mer arbeid enn det vi har tid og kapasitet til.
