### ISSUE TITLE
Fugle og vind lyder spiller av hele tiden.

### ISSUE THREAD

**Issue by Tobb50** [FunkWeb/spill6#156]
De nye bakgrunnslydene med fugler å vind spilles av konstant, uansett om man er i hovedmenyen, en annen undermeny eller spiller selve brettet. Dette burde fikses, slik at det bare spilles av i hovedmenyen, hvor den passer best. Siden den er for rolig til å ta opp så mye av lydbilde i spillbrettet.

v0.1.6-alpha

**Comment by nycofox** [comment]
Vi bestemte at bakgrunnslyden kun skal spilles på hovedmenyen og i krediterings-delen.
