### ISSUE TITLE
Bakgrunnslyden har ujevnt lydnivå og repeteres merkbart

### ISSUE THREAD

**Issue by nycofox** [FunkWeb/spill6#162]
La merke til at den ikke looper helt bra, volumet på begynnelsen og slutten er på ulike nivåer, og man hører tydelig når den starter på nytt.

Testet på v0.1.6a

**Comment by nycofox** [comment]
Denne venter på ny original-fil før vi setter den til implementering lokalt

**Comment by NorskViking** [comment]
Dennis er satt på saken om å fikse lydfilen.

**Comment by Tobb50** [comment]
https://drive.google.com/file/d/1cRHBBpv4vjdbsSqF4f9pMEDOpNXVDXU5/view?usp=drive_link
Dennis har laget en ny lyd, men nå må den implementeres og byttes ut med den gamle
