### ISSUE TITLE
Spiller karakter oppleves som liten v0.1.8

### ISSUE THREAD

**Issue by NorskViking** [FunkWeb/spill6#174]
Zoome inn kameraet?

**Comment by LongJumpProduction** [comment]
Værsåsnill ikke zoom inn kameraet enda mer en det alt er. Det vil ødelegge bakgrunnen blandt annet

**Comment by Tobb50** [comment]
Å endret zoomen medfører at spilleren i mange tilfeller ikke klarer å se innkommende hindrer siden kameraet følger Raskeladden oppover. Så vil si at dette er en mer omfattende oppgave som vi ikke har tid til å fikse. Dessuten ser det godt nok ut til å fungere per nå.

**Comment by ghost** [comment]
Er dette fortsatt et problem etter #205 ?
