### ISSUE TITLE
Pauseknapp ved seier sender deg vidre, men gjør det umulig å klikke på noe som helst annet.

### ISSUE THREAD

**Issue by eturenuR** [FunkWeb/spill6#179]
![Screenshot_20240312_184412](https://github.com/FunkWeb/spill6/assets/145231978/906047f6-17b9-4753-96d2-7325ce08dd01)

Trykket pause rett før "seier" og får denne fine effekten.

**Comment by NorskViking** [comment]
Er det selv etter mergen av en issue #172 som jeg fikset i går?

**Comment by eturenuR** [comment]
Det er v0.1.8 apk.

Om denne blei laget før eller etter bugfiksen har jeg ikke sjekket, men siden den tidligere "issuen" var fjernet før jeg lagde min, så antok jeg at dette var inkludert.

**Comment by Tobb50** [comment]
Testet nettopp og det er umulig å klikke på pause knappen når man vinner, siden knappen forsvinner sekundet du vinner. Vet ikke når dette har blitt fikset.

**Comment by ghost** [comment]
Dette kan også skje hvis man faller ned hull og trykker på pauseknappen, eller pauser med tilbakeknapp ved mål, hull eller tom for liv.
