### ISSUE TITLE
Legge til app logo

### ISSUE THREAD

**Issue by vsgj** [FunkWeb/spill6#180]
App logoen er ferdigstilt og klar til å legges til i prosjektet. I mappen ligger det en 1024x1024 versjon og en 512x512 versjon. I følge internett er disse de vanlige oppløsningene for app-ikoner og 1024x1024 er mest brukt.

[App logo mappe](https://drive.google.com/drive/folders/1DAXAtloBA8jnGUgXK63v-p5tUZW-8xZV)

**Comment by nycofox** [comment]
@Tormod-Rasmussen - legges denne inn i selve spillet? Jeg tar den ellers om den kun skal legges til via prosjekt-eksporten.
