### ISSUE TITLE
Hopp-animasjonen.

### ISSUE THREAD

**Issue by Day-Robyn** [FunkWeb/spill6#182]
Flott implementering av hopp-animashonen, men den er lagt inn i feil rekkefølge. Det er meningen at han skal bøye seg ned og så hoppe. I spillet nå bøyer han seg ned på det høyeste i lufta. I og for seg ser det ikke så ille ut. men det er altså feil. ^_^*

**Comment by nycofox** [comment]
Prøv også å skalere opp størrelsen litt på Raskeladden
