### ISSUE TITLE
v.0.1.8 - Karakter hopper litt høyt ?

### ISSUE THREAD

**Issue by Gnomleif** [FunkWeb/spill6#190]
Vet ikke om det er tiltenkt, men opplever at karakter hopper litt unormalt høyt og som resulterer i at man mister syn av bakken og hindringer som kommer enkelte steder fordi kamera jo følger karakter.
Om dette er tiltenkt så se bort i fra dette.

Men fra en spillers perspektiv kan det oppleves noe i høyeste laget :)

**Comment by Bounzpalooza** [comment]
v0.2.2: Velger bare å svare her i stedet for å lage en ny tråd. 


Jeg har testet litt ulike verdier på jump_velocity. Noe dere sikkert også har gjort. Fant at verdier (jump_velocity) på rundt -340, -330, -350 fungerer bra om tanken er at karakteren skal hoppe lavere. Henholdsvis med vanskelighetsgraden mer balansert, mer på "hoppsats", eller for å unngå for langt nedslag som gjør at man treffer neste hinder (-350). 

Dette blir så klart en "design decision" da. Slik hindrene på level 1 er satt opp så vil kanskje verdier mellom 330-350 kunne fungere? Forslag i tilfelle på jump_velocity: float = -340.0 ?

Som nevnt i OP her, så er det bare å ignorere innspillet om nåværende høyde er tiltenkt fra et design perspektiv:)

En annen ide (som jeg forstår kanskje ikke er mulig på nåværende tidspunkt) kan jo være ulike "powerups" (?) som potensielt endrer 'hoppstørrelsen' til Raskeladden; men bare noen løse tanker så klart. 

Min feeling på spillet er sikkert også i stor grad farget av lang erfaring med de første super mario bros. spillene:)

Disse verdiene ble testet med både ekstern mus og touchpad-klikk. Kan kanskje være verdt å leke seg litt med disse uansett for å finne riktig "feeling" på spillbarheten. 

Kan det være verdt å lansere noen ulike "release kandidater" til testing på mobil, med ulike verdier?


Mvh, 
Ole
