### ISSUE TITLE
Redusere filstørelse av art assets

### ISSUE THREAD

**Issue by NorskViking** [FunkWeb/spill6#202]
Mange av art assetene har et stort tomrom rundt selve bildet. 'Crop' bilde filene til å være tettere rundt selve bildet. Dette vil kunne spare noen kb pr. fil.

**Comment by LongJumpProduction** [comment]
Jeg kan bare snakke for bakgrunnen siden jeg lagde den, men jeg ble fortalt i ett møte at den skulle lages større enn det skjermen vinduet i spillet er i tilfelle spillet skulle spilles av på foreksempel en Ipad eller en annen stor skjerm slik at ikke det blir masse 'void' på kantene.

**Comment by hanseei** [comment]
Sånn jeg forstod det skulle bildefilene være kvadratiske og PoT, men om det ikke er viktig kan jeg fint croppe teksturene mine ganske kjapt.

**Comment by LongJumpProduction** [comment]
Jeg misforstod litt på den første komentaren min, så ignorer den.

Jeg har nå reimportert bakgrunnen sine lag slik at de nå har mindre tomrom rundt seg. Men det er alt jeg har gjort da.

**Comment by LongJumpProduction** [comment]
Sorry jeg closet issuen med ett uhell, å måtte åpne den på nytt. Se bort ifra det
