### ISSUE TITLE
Tydelig strek over bakgrunnen [v0.2.1-beta]

### ISSUE THREAD

**Issue by nycofox** [FunkWeb/spill6#203]
v0.2.1-beta

Når man kommer litt inn i første bane, log litt opp i terrenget, så er den en synlig strek som ligger i bakgrunnen, se bilde under.

Oppstår både på android og web-versjonen.

![Screenshot_20240313_170246_Raskeladden og Dovreslubben](https://github.com/FunkWeb/spill6/assets/456280/441099c0-e5fc-4a4e-be60-918520da7716)

**Comment by ghost** [comment]
Denne skulle blitt fikset i #188 og er fikset når jeg tester i debug.

Kan du sjekke om default_texture_repeat er satt til Disable på din Godot? det er under project settings rendering/textures/canvas_textures/default_texture_repeat

**Comment by nycofox** [comment]
Står med verdien "Disable" når jeg sjekker

![image](https://github.com/FunkWeb/spill6/assets/456280/abb2ec3e-f963-4eaf-89d0-54ea3e1ffe43)

**Comment by ghost** [comment]
Jeg lagde en apk av dev branchen og den har ikke strek. Vet ikke hvorfor den dukker opp i v0.2.1-beta
![image](https://github.com/FunkWeb/spill6/assets/115534962/48b3e5a5-5498-4413-96b8-006d52b5656f)

**Comment by ghost** [comment]
Lukker denne siden den er fikset i #188
