### ISSUE TITLE
Escape-tasten mens du ser på introduksjonssekvensen gir deg pausemenyen

### ISSUE THREAD

**Issue by eturenuR** [FunkWeb/spill6#241]
v0.2.3

Igjen, gjelder ikke mobil og egentlig bare for pc, eventuelt nettleser, men nevner det likevel:

Hvis du trykker "Escape"-tasten under introduksjonssekvensen får du opp pausemenyen, som kan virke litt merkelig.

**Comment by ghost** [comment]
Dette kan også skje ved trykk på tilbakeknapp på android
