### ISSUE TITLE
Spilleren forblir i live til tross for tomme hjerter

### ISSUE THREAD

**Issue by Tobb50** [FunkWeb/spill6#52]
Når man nå går tom for hjerter mens man spiller, så dør ikke spilleren. 

Spilleren mister liv dersom han har liv i HUD-en men selv om alle hjertene er vekke så dør ikke spilleren.

**Comment by nycofox** [comment]
@Tobb50 - skriv på norsk, ikke engelsk. Jeg endret tittelen.

**Comment by Tobb50** [comment]
Unnskyld, detter inn litt automatisk. Prøver å ta tak i det videre.

**Comment by pat955** [comment]
Sorry trykket feil, ignorer det!

**Comment by nycofox** [comment]
Løst i Pull Request
