### ISSUE TITLE
Figuren blir stillestående eller går baklengs hvis du stanger hodet i taket

### ISSUE THREAD

**Issue by eturenuR** [FunkWeb/spill6#71]
Omtrent halvveis, når du kommer inn i "hulegangen" så kan du dobbelthoppe og stange hodet i taket. Hver gang du gjør dette så senker farten seg. Gjør du det enda et par ganger så beveger du deg baklengs. Og hvis du rekker å gjøre det enda flere ganger før du slipper opp for tak, så begynner du å bevege deg framover igjen.

**Comment by ghost** [comment]
Åpner denne igjen da man fortsatt kan senke farten ved å treffe taket i den andre hulen.

**Comment by ghost** [comment]
Godot sin fysikk motor endrer velocity når du kolliderer med ting. Dette gjør at du før minus velocity og begynner å bevege deg bakover når du hopper inn i taket.
enkel løsning blir vel å sette velocity.x til 0 hver frame.

Spilleren bruker per nå ikke velocity til å bevege seg fremover, men setter position.x += scroll_speed * delta. altså hver frame hopper spilleren fram noen pixler.
