### ISSUE TITLE
Dårlige kollisjons med CharactherBody2D med Map Addon

### ISSUE THREAD

**Issue by JonathanPR-Github** [FunkWeb/spill6#83]
Addonen som jeg bruker fungerer ikke bra når spilleren skal ned brette bakker, raskeladden spretter opp og ned man kan ikke hoppe før raskeladden når et punkt av bakken.

**Comment by ghost** [comment]
Kunne løses med coyote time så du kan hoppe litt etter du mistet bakkekontakt, men vi burde få spilleren til å holde seg på bakken så fall animasjon ikke spilles når den blir implementert.
