### ISSUE TITLE
pause fryser spillet hvis man har dødd

### ISSUE THREAD

**Issue by ghost** [FunkWeb/spill6#89]
Pauser man spillet etter at man har tapt eller vunnet, men før spillet går tilbake til menyen fryser spillet.

**Comment by EkebergByte** [comment]
v0. 1-3.alpha

system log når man prøver å klikke på noe i innstillingene etter at en karakter har dødd:

![Screenshot_20240304_205438_LogCat](https://github.com/FunkWeb/spill6/assets/162102955/b381d98b-31e9-4e60-9e88-b7f66c7de437)

**Comment by hanseei** [comment]
Ser ut som om det er noe feil rekkefølge på destruering av objekter - spillet prøver å kjøre kode som refererer til ting som har blitt ødelagt.

**Comment by Taxato** [comment]
Burde kunne fikses ved å bare disable pausemenyen når man dør
