### ISSUE TITLE
Forhindre redigering av krediteringstekst

### ISSUE THREAD

**Issue by EkebergByte** [FunkWeb/spill6#92]
versjonen: 0.1.1-alpha
enheten: SM-G988B/DS

Når jeg går inn på fanen Kreditering i hovedmenyen og trykker hvor som helst på skjermen, åpnes tastaturet. 

Det er ikke mulig å se det på bildet, men i hjørnet der skjermen er avrundet, er ordet "Author" beskåret slik at bare bokstavene "hor" er synlige.

![Screenshot_20240303_162018_Raskeladden og Dovreslubben](https://github.com/FunkWeb/spill6/assets/162102955/2a17be4d-8b85-4a00-be30-32f2878e155b)
![Screenshot_20240304_091840_Raskeladden og Dovreslubben](https://github.com/FunkWeb/spill6/assets/162102955/7c4195e1-12b1-4183-9df1-07733edb3fea)

**Comment by nycofox** [comment]
Ser det samme her, bra tilbakemelding 👍

**Comment by LongJumpProduction** [comment]
Jeg er ganske sikker på at jeg har fikset det nå, men jeg har ikke testet på mobil
