### ISSUE TITLE
Fjerne test-brettet 

### ISSUE THREAD

**Issue by nycofox** [FunkWeb/spill6#93]
Dette brettet fungerer ikke og skal ikke være med i releaser.

**Comment by eturenuR** [comment]
Du kan heller ikke komme deg ut av dette brettet uten å avslutte Godot eller appen. Tidligere døde du, men det gjør du ikke lenger (v0.1.4).

**Comment by nycofox** [comment]
@LongJumpProduction - Hva er status her? Hvis denne ikke blir klar i dag må jeg sette den til noen andre.

**Comment by LongJumpProduction** [comment]
Jeg planlegger å få den gjort idag

**Comment by LongJumpProduction** [comment]
Jeg har gjort den nå

**Comment by nycofox** [comment]
Det ligger fremdeles i kartet

**Comment by NorskViking** [comment]
Merge av #176 har nå fikset dette.
