### ISSUE TITLE
"Umulig" å fullføre første bane

### ISSUE THREAD

**Issue by Taxato** [FunkWeb/spill6#96]
Pga. down-slope buggen som forhindrer hopping, er det flere fiender det praktisk talt er umulig å unngå, og dermed gjør banen ekstremt vanskelig

**Comment by Taxato** [comment]
I tillegg til fiender er det et hull i bunnen av en slope, som er instant death hvis man ikke kan hoppe

**Comment by eturenuR** [comment]
Vil tippe dette er relatert til issue #83

**Comment by nycofox** [comment]
Duplikat av #83, stenger denne
