### ISSUE TITLE
Hovedmeny-skilter bruker gamle teksturer

### ISSUE THREAD

**Issue by hanseei** [FunkWeb/spill6#98]
Nye teksturer ligger i samme mappe som de forrige i google drive. De nye har tykkere kantlinje og litt detalj på treverket. Mangler også pålen som skal være bak, teksturen ligger i undermappen 'ekstra'.

**Comment by NorskViking** [comment]
Nye skilt teksturerer lagt inn og erstattet de gamle. Ny stolpe tekstur lagt inn i hovedmeny,
